services:
  app:
    build: .
    volumes:
      - .:/django_app
    ports:
      - "8000:8000"
    image: app:django_app
    container_name: django_app_container
    command: python manage.py runserver 0.0.0.0:8000

